eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/

#设置超时时间
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 2000
        read-timeout: 4000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
#设置负载均衡策略
  #product-service:
    #ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
server:
  port: 8880
spring:
  application:
    name: order-service
  zipkin:
    base-url: http://192.168.30.129:9411/
  sleuth:
    sampler: 1
logging:
  level:
    web: trace
    sql: debug  # mybatis 日志
#配置文件增加endpoint 打开监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
