version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    restart: always
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    restart: always
    environment:
      ELASTICSEARCH_URL: "127.0.0.1:9200"
      I18N_LOCALE: "zh-CN"
    ports:
      - "5601:5601"
  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE: elasticsearch
      - ES_HOSTS: "127.0.0.1:9200"
    ports:
      - "9411:9411"
